version: '3.3'

services:  #In services we mention containers
  flask:   #flask container
    image: sohailshaikh23/2-tier_flask:latest
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - 2-tier
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  mysql:   #mysql container 
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - 2-tier
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql   #bind mount with host machine directory
      - mysql-data:/var/lib/mysql                           #docker volume

volumes:
  mysql-data:
networks:
  2-tier:
