apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels: 
      app: flask
spec:
  containers:
  - name: flask-container
    image: sohailshaikh23/flaskapp:latest
    env:
      - name: MYSQL_HOST
        value: "mysql"          # this is your mysql's service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "admin"
      - name: MYSQL_DB
        value: "mydb"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
    
