apiVersion: v1  #AKM section
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:            #config map data 
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);
