apiVersion: apps/v1   #AKM section
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:                #deployment spec section
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:          #pod template starts
    metadata:
      labels:
        app: mysql
    spec:            #pod spec section
      containers:
        - name: mysql
          image: sohailshaikh23/2-tier_mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "mydb"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: docker-entrypoint-initdb.d #its content will run first
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config    # Config name
